/*
 * @bot-written
 *
 * WARNING AND NOTICE
 * Any access, download, storage, and/or use of this source code is subject to the terms and conditions of the
 * Full Software Licence as accepted by you before being granted access to this source code and other materials,
 * the terms of which can be accessed on the Codebots website at https://codebots.com/full-software-licence. Any
 * commercial use in contravention of the terms of the Full Software Licence may be pursued by Codebots through
 * licence termination and further legal action, and be required to indemnify Codebots for any loss or damage,
 * including interest and costs. You are deemed to have accepted the terms of the Full Software Licence on any
 * access, download, storage, and/or use of this source code.
 *
 * BOT WARNING
 * This file is bot-written.
 * Any changes out side of "protected regions" will be lost next time the bot makes any changes.
 */

import { ActivatedRoute } from '@angular/router';
import { BehaviorSubject } from 'rxjs';
import { By } from '@angular/platform-browser';
import { ComponentFixture, TestBed, waitForAsync, fakeAsync } from '@angular/core/testing';
import { CookieService } from 'ngx-cookie-service';
import { DebugElement } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { Store } from '@ngrx/store';
import { MockStore, provideMockStore } from '@ngrx/store/testing';
import { ModalDialogService, ModalDialogInstanceService } from '@preeco-privacy/ngx-modal-dialog';
import { ActivatedRouteStub } from 'src/testing/helpers/activated-route-stub';
import { CommonComponentModule } from 'src/app/lib/components/common.component.module';
import { getRouterState } from 'src/app/models/model.selector';
import { RouterState } from 'src/app/models/model.state';
import { 
	getBpjsSEPInternalDataCollectionModels,
	getCountBpjsSEPInternalDataModels,
	getBpjsSEPInternalDataModelWithId
} from 'src/app/models/bpjsSEPInternalData/bpjs_sep_internal_data.model.selector';
import { BpjsSEPInternalDataCrudModule } from '../bpjs-sep-internal-data-crud.module';
import { BpjsSEPInternalDataCrudEditComponent } from './bpjs-sep-internal-data-crud-edit.component';
import {
	BpjsSEPInternalDataModelState,
	initialState as initialBpjsSEPInternalDataModelState
} from 'src/app/models/bpjsSEPInternalData/bpjs_sep_internal_data.model.state';
import { BpjsSEPInternalDataDataFactory } from 'src/app/lib/utils/factories/bpjs-sep-internal-data-data-factory';
import { BpjsSEPInternalDataModel } from 'src/app/models/bpjsSEPInternalData/bpjs_sep_internal_data.model';
import { CrudTileMode } from '../bpjs-sep-internal-data-crud.component';

describe('BPJS SEP Internal Data CRUD Edit component tests', () => {
	let fixture: ComponentFixture<BpjsSEPInternalDataCrudEditComponent>
	let component: BpjsSEPInternalDataCrudEditComponent;

	let bpjsSEPInternalDataModelState: BpjsSEPInternalDataModelState;

	let store: MockStore<{ model: BpjsSEPInternalDataModelState }>;
	let routerStore: MockStore<{router: RouterState}>;

	let routerStateBehaviorSubject: BehaviorSubject<RouterState>;
	let bpjsSEPInternalDataCountBehaviorSubject: BehaviorSubject<number>;
	let bpjsSEPInternalDataModelsBehaviorSubject: BehaviorSubject<BpjsSEPInternalDataModel[]>;

	const bpjsSEPInternalDataFactory: BpjsSEPInternalDataDataFactory = new BpjsSEPInternalDataDataFactory();
	const defaultBpjsSEPInternalDataCount: number = 10;
	const defaultBpjsSEPInternalDataEntities: BpjsSEPInternalDataModel[] = bpjsSEPInternalDataFactory.createAll(defaultBpjsSEPInternalDataCount);


	// We define the entity which is used in edit mode after all of the other entities because we can now
	// use the data already generated by the previous entity factories to populate the relations of this entity
	let bpjsSEPInternalDataWithId: BpjsSEPInternalDataModel = defaultBpjsSEPInternalDataEntities[0];
	let bpjsSEPInternalDataModelWithIdBehaviorSubject: BehaviorSubject<BpjsSEPInternalDataModel>;


	const routerState: RouterState = {
		url: 'bpjs-sep-internal-data-crud',
		urls: ['bpjs-sep-internal-data-crud'],
		params: {},
		queryParams: {},
		data: {},
	};

	function spySelectorsInStore() {
		// Setup the Mock Store and fake selector
		store = TestBed.inject(Store) as MockStore<{ model: BpjsSEPInternalDataModelState }>;
		routerStore = TestBed.inject(Store) as MockStore<{ router: RouterState }>;

		bpjsSEPInternalDataModelState = initialBpjsSEPInternalDataModelState;
		store.setState({model: bpjsSEPInternalDataModelState});
		routerStateBehaviorSubject = new BehaviorSubject(routerState);
		bpjsSEPInternalDataCountBehaviorSubject = new BehaviorSubject(defaultBpjsSEPInternalDataCount);

		// selectors for all references
		bpjsSEPInternalDataModelsBehaviorSubject = new BehaviorSubject(defaultBpjsSEPInternalDataEntities);

		// selectors for target entity and its related entity
		bpjsSEPInternalDataModelWithIdBehaviorSubject = new BehaviorSubject(bpjsSEPInternalDataWithId);

		spyOn(store, 'select')
			.withArgs(getCountBpjsSEPInternalDataModels).and.returnValue(bpjsSEPInternalDataCountBehaviorSubject)
			.withArgs(getBpjsSEPInternalDataModelWithId, bpjsSEPInternalDataWithId.id).and.returnValue(bpjsSEPInternalDataModelWithIdBehaviorSubject)
			.withArgs(getBpjsSEPInternalDataCollectionModels, jasmine.any(String)).and.returnValue(bpjsSEPInternalDataModelsBehaviorSubject)
			.withArgs(getRouterState).and.returnValue(routerStateBehaviorSubject);
	}

	beforeEach(waitForAsync (() => {

		const activatedRouteStub = new ActivatedRouteStub();

		TestBed.configureTestingModule({
			imports: [
				HttpClientTestingModule,
				BpjsSEPInternalDataCrudModule,
				CommonComponentModule,
				FormsModule,
				ReactiveFormsModule,
			],
			providers: [
				provideMockStore(),
				{
					provide: ActivatedRoute,
					useValue: activatedRouteStub,
				},
				CookieService,
				ModalDialogService,
				ModalDialogInstanceService,
			]
		}).compileComponents().then(() => {

			spySelectorsInStore();

			fixture = TestBed.createComponent(BpjsSEPInternalDataCrudEditComponent);
			component = fixture.debugElement.componentInstance;
			component.ngOnInit();
			component.targetModel = new BpjsSEPInternalDataModel();
			component.createReactiveForm();
			fixture.detectChanges();


		});
	}));

	afterEach(() => {
		// Need to do this since for some reason the last component queried from the fixture will be rendered on the
		// browser
		if (fixture.nativeElement instanceof HTMLElement) {
			(fixture.nativeElement as HTMLElement).remove();
		}
		component.ngOnDestroy();
	});

	/**
	 * Checks that the component is created by the test initialisation
	 */
	it ('Renders the BPJS SEP Internal Data CRUD Edit Component', () => {
		expect(component).toBeTruthy();
	});

	/**
	 * Checks that there are no add additional model buttons present in the component when in view mode.
	 *
	 * This test does not require checking whether multi crud is active for a given relation, as the expected outcome
	 * is identical for components with multi entity crud active and for components without it
	 */
	it ('Does not render any add entity buttons when in view mode', fakeAsync(() => {
		component.tileMode = CrudTileMode.View;
		fixture.detectChanges();

		const addEntityButtons: DebugElement[] = fixture.debugElement
				.queryAll(By.css('button.btn__add-entity'));

		expect(addEntityButtons.length).toEqual(0);
	}));

});
