/*
 * @bot-written
 *
 * WARNING AND NOTICE
 * Any access, download, storage, and/or use of this source code is subject to the terms and conditions of the
 * Full Software Licence as accepted by you before being granted access to this source code and other materials,
 * the terms of which can be accessed on the Codebots website at https://codebots.com/full-software-licence. Any
 * commercial use in contravention of the terms of the Full Software Licence may be pursued by Codebots through
 * licence termination and further legal action, and be required to indemnify Codebots for any loss or damage,
 * including interest and costs. You are deemed to have accepted the terms of the Full Software Licence on any
 * access, download, storage, and/or use of this source code.
 *
 * BOT WARNING
 * This file is bot-written.
 * Any changes out side of "protected regions" will be lost next time the bot makes any changes.
 */
import {FormGroup, Validators} from '@angular/forms';
import {Group, AbstractModel, ModelProperty, ModelPropertyType, ModelRelation, ModelRelationType} from '../../lib/models/abstract.model';
import {PatientGeneralInfoModel} from '../patientGeneralInfo/patient_general_info.model';
import * as _ from 'lodash';
import {QueryOperation, Where} from '../../lib/services/http/interfaces';
import {ElementType} from '../../lib/components/abstract.input.component';
import { CustomValidators } from 'src/app/lib/utils/validators/custom-validators';

// % protected region % [Add any additional imports here] off begin
// % protected region % [Add any additional imports here] end

/**
 * POJO model class used to store information related to the entity.
 */
export class PatientDetailModel extends AbstractModel {
	/**
	 * The fields which are set as searchable in the entity model
	 * The fields could be used in search in the server side
	 * The fields would be by default used as search in the crud tile.
	 * You could also use this in other tiles for searching.
	 */
	static searchFields: string[] = [
		// % protected region % [Add any additional searchable field names here] off begin
		// % protected region % [Add any additional searchable field names here] end
	];

	/**
	 * Attributes to be shown in value to display
	 */
	static displayAttributes: string[] = [
		// % protected region % [Change displayAttributes here if needed] off begin
		'activePatientID',
		// % protected region % [Change displayAttributes here if needed] end
	];

	static modelPropGroups: { [s: string]: Group } = {
		// % protected region % [Add groups for the entity here] off begin
		// % protected region % [Add groups for the entity here] end
	};

	readonly className = 'PatientDetailModel';

	/**
	 * Default value to be displayed in dropdown etc
	 */
	get valueToDisplay(): string {
		// % protected region % [Change displayName here if needed] off begin
		return PatientDetailModel.displayAttributes.map((attr) => this[attr]).join(' ');
		// % protected region % [Change displayName here if needed] end
	}

	/**
	 * Reference/merge to active Patient ID. This ID will link the medical record patient. By default, it refers/copies from Patient ID, generated by system (Max Length: 50).
	 */
	activePatientID: string;

	/**
	 * Classification patient, get the Code from Reference Data where Type=PATIENT_CLASS. (Max Length: 20).
	 */
	patientClassification: string;

	/**
	 * Patient Type data, get from Reference Type: PATIENT_TYPE (Max Length: 20).
	 */
	patientType: string;

	/**
	 * Status of married of patient, get the Code from Reference Data where Type=MARITAL_STAT (Max Length: 20).
	 */
	maritalStatus: string;

	/**
	 * Notes (max Length: 500).
	 */
	notes: string;

	patientGeneralInformationId: string;

	patientGeneralInformation: PatientGeneralInfoModel;

	modelPropGroups: { [s: string]: Group } = PatientDetailModel.modelPropGroups;

	// % protected region % [Add any additional class fields here] off begin
	// % protected region % [Add any additional class fields here] end

	static getProps(): ModelProperty[] {
		return super.getProps().concat([
			{
				name: 'activePatientID',
				// % protected region % [Set displayName for Active Patient ID here] off begin
				displayName: 'Active Patient ID',
				// % protected region % [Set displayName for Active Patient ID here] end
				type: ModelPropertyType.STRING,
				// % protected region % [Set display element type for Active Patient ID here] off begin
				elementType: ElementType.INPUT,
				// % protected region % [Set display element type for Active Patient ID here] end
				// % protected region % [Set isSensitive for Active Patient ID here] off begin
				isSensitive: false,
				// % protected region % [Set isSensitive for Active Patient ID here] end
				// % protected region % [Set readonly for Active Patient ID here] off begin
				readOnly: false,
				// % protected region % [Set readonly for Active Patient ID here] end
				validators: [
					Validators.required,
					CustomValidators.nonEmptyString(),
					// % protected region % [Add other validators for Active Patient ID here] off begin
					// % protected region % [Add other validators for Active Patient ID here] end
				],
				// % protected region % [Add any additional model attribute properties for Active Patient ID here] off begin
				// % protected region % [Add any additional model attribute properties for Active Patient ID here] end
			},
			{
				name: 'patientClassification',
				// % protected region % [Set displayName for Patient Classification here] off begin
				displayName: 'Patient Classification',
				// % protected region % [Set displayName for Patient Classification here] end
				type: ModelPropertyType.STRING,
				// % protected region % [Set display element type for Patient Classification here] off begin
				elementType: ElementType.INPUT,
				// % protected region % [Set display element type for Patient Classification here] end
				// % protected region % [Set isSensitive for Patient Classification here] off begin
				isSensitive: false,
				// % protected region % [Set isSensitive for Patient Classification here] end
				// % protected region % [Set readonly for Patient Classification here] off begin
				readOnly: false,
				// % protected region % [Set readonly for Patient Classification here] end
				validators: [
					// % protected region % [Add other validators for Patient Classification here] off begin
					// % protected region % [Add other validators for Patient Classification here] end
				],
				// % protected region % [Add any additional model attribute properties for Patient Classification here] off begin
				// % protected region % [Add any additional model attribute properties for Patient Classification here] end
			},
			{
				name: 'patientType',
				// % protected region % [Set displayName for Patient Type here] off begin
				displayName: 'Patient Type',
				// % protected region % [Set displayName for Patient Type here] end
				type: ModelPropertyType.STRING,
				// % protected region % [Set display element type for Patient Type here] off begin
				elementType: ElementType.INPUT,
				// % protected region % [Set display element type for Patient Type here] end
				// % protected region % [Set isSensitive for Patient Type here] off begin
				isSensitive: false,
				// % protected region % [Set isSensitive for Patient Type here] end
				// % protected region % [Set readonly for Patient Type here] off begin
				readOnly: false,
				// % protected region % [Set readonly for Patient Type here] end
				validators: [
					// % protected region % [Add other validators for Patient Type here] off begin
					// % protected region % [Add other validators for Patient Type here] end
				],
				// % protected region % [Add any additional model attribute properties for Patient Type here] off begin
				// % protected region % [Add any additional model attribute properties for Patient Type here] end
			},
			{
				name: 'maritalStatus',
				// % protected region % [Set displayName for Marital Status here] off begin
				displayName: 'Marital Status',
				// % protected region % [Set displayName for Marital Status here] end
				type: ModelPropertyType.STRING,
				// % protected region % [Set display element type for Marital Status here] off begin
				elementType: ElementType.INPUT,
				// % protected region % [Set display element type for Marital Status here] end
				// % protected region % [Set isSensitive for Marital Status here] off begin
				isSensitive: false,
				// % protected region % [Set isSensitive for Marital Status here] end
				// % protected region % [Set readonly for Marital Status here] off begin
				readOnly: false,
				// % protected region % [Set readonly for Marital Status here] end
				validators: [
					// % protected region % [Add other validators for Marital Status here] off begin
					// % protected region % [Add other validators for Marital Status here] end
				],
				// % protected region % [Add any additional model attribute properties for Marital Status here] off begin
				// % protected region % [Add any additional model attribute properties for Marital Status here] end
			},
			{
				name: 'notes',
				// % protected region % [Set displayName for Notes here] off begin
				displayName: 'Notes',
				// % protected region % [Set displayName for Notes here] end
				type: ModelPropertyType.STRING,
				// % protected region % [Set display element type for Notes here] off begin
				elementType: ElementType.INPUT,
				// % protected region % [Set display element type for Notes here] end
				// % protected region % [Set isSensitive for Notes here] off begin
				isSensitive: false,
				// % protected region % [Set isSensitive for Notes here] end
				// % protected region % [Set readonly for Notes here] off begin
				readOnly: false,
				// % protected region % [Set readonly for Notes here] end
				validators: [
					// % protected region % [Add other validators for Notes here] off begin
					// % protected region % [Add other validators for Notes here] end
				],
				// % protected region % [Add any additional model attribute properties for Notes here] off begin
				// % protected region % [Add any additional model attribute properties for Notes here] end
			},
			// % protected region % [Add any additional class field names here] off begin
			// % protected region % [Add any additional class field names here] end
		]);
	}

	/**
	 * The relations of the entity
	 */
	static getRelations(): ModelRelation[] {
		return super.getRelations().concat([
			{
				id: 'patientGeneralInformation',
				type: ModelRelationType.ONE,
				name: 'patientGeneralInformationId',
				// % protected region % [Customise your label for Patient General Information here] off begin
				label: 'Patient General Information',
				// % protected region % [Customise your label for Patient General Information here] end
				entityName: 'PatientGeneralInfoModel',
				// % protected region % [Customise your display name for Patient General Information here] off begin
				// TODO change implementation to use OrderBy or create new metamodel property DisplayBy
				displayName: 'patientID',
				// % protected region % [Customise your display name for Patient General Information here] end
				validators: [
					// % protected region % [Add other validators for Patient General Information here] off begin
					// % protected region % [Add other validators for Patient General Information here] end
				],
				// % protected region % [Add any additional field for relation Patient General Information here] off begin
				// % protected region % [Add any additional field for relation Patient General Information here] end
			},
		]);
	}

	/**
	 * Convert the form group to the query conditions
	 */
	static convertFilterToCondition(formGroup: FormGroup): Where[][] {
		let conditions: Where[][] = [];

		// % protected region % [Overide the default convertFilterToCondition here] off begin
		Object.keys(formGroup.value).forEach((key) => {
			switch (key) {
				case 'created':
					const created = formGroup.value[key];
					// is the range of date
					if (created instanceof Array) {
						conditions.push([
							{
								path: key,
								operation: QueryOperation.GREATER_THAN_OR_EQUAL,
								value: created[0]
							}
						]);
						conditions.push([
							{
								path: key,
								operation: QueryOperation.LESS_THAN_OR_EQUAL,
								value: created[1]
							}
						]);
					}
			}
		});
		// % protected region % [Overide the default convertFilterToCondition here] end


		return conditions;
	}

	/**
	 * Convert a nested JSON object into an array of flatten objects.
	 */
	static deepParse(data: string | { [K in keyof PatientDetailModel]?: PatientDetailModel[K] }, currentModel?): AbstractModel[] {
		if (currentModel == null) {
			currentModel = new PatientDetailModel(data);
		}

		let returned: AbstractModel[] = [currentModel];
		const json = typeof data === 'string' ? JSON.parse(data) : data;

		// Incoming one to one
		if (json.patientGeneralInformation) {
			currentModel.patientGeneralInformationId = json.patientGeneralInformation.id;
			returned = _.union(returned, PatientGeneralInfoModel.deepParse(json.patientGeneralInformation));
		}


		// % protected region % [Customise your deep parse before return here] off begin
		// % protected region % [Customise your deep parse before return here] end

		return returned;
	}

	/**
	 * @example
	 *
	 * `let patientDetailModel = new PatientDetailModel(data);`
	 *
	 * @param data The input data to be initialised as the PatientDetailModel,
	 *    it is expected as a JSON string or as a nullable PatientDetailModel.
	 */
	constructor(data?: string | Partial<PatientDetailModel>) {
		super(data);

		if (data) {
			const json = typeof data === 'string'
				? JSON.parse(data) as Partial<PatientDetailModel>
				: data;

			this.activePatientID = json.activePatientID;
			this.patientClassification = json.patientClassification;
			this.patientType = json.patientType;
			this.maritalStatus = json.maritalStatus;
			this.notes = json.notes;
			this.patientGeneralInformationId = json.patientGeneralInformationId;
			this.patientGeneralInformation = json.patientGeneralInformation;
			// % protected region % [Add any additional logic here after set the data] off begin
			// % protected region % [Add any additional logic here after set the data] end
		}

		// % protected region % [Add any additional constructor logic here] off begin
		// % protected region % [Add any additional constructor logic here] end
	}

	toJSON() {
		return {
			...super.toJSON(),
			activePatientID: this.activePatientID,
			patientClassification: this.patientClassification,
			patientType: this.patientType,
			maritalStatus: this.maritalStatus,
			notes: this.notes,
			patientGeneralInformationId: this.patientGeneralInformationId,
			// % protected region % [Add any additional logic here to json] off begin
			// % protected region % [Add any additional logic here to json] end
		};
	}

	getPropDisplayNames(): { [s: string]: ModelProperty } {
		const returned = {};
		PatientDetailModel.getProps().map(prop => returned[prop.name] = prop);
		return returned;
	}

	applyUpdates(updates: any): PatientDetailModel {
		let newModelJson = this.toJSON();

		if (updates.activePatientID) {
			newModelJson.activePatientID = updates.activePatientID;
		}

		if (updates.patientClassification) {
			newModelJson.patientClassification = updates.patientClassification;
		}

		if (updates.patientType) {
			newModelJson.patientType = updates.patientType;
		}

		if (updates.maritalStatus) {
			newModelJson.maritalStatus = updates.maritalStatus;
		}

		if (updates.notes) {
			newModelJson.notes = updates.notes;
		}

		if (updates.patientGeneralInformationId) {
			newModelJson.patientGeneralInformationId = updates.patientGeneralInformationId;
		}

		return new PatientDetailModel(newModelJson);
	}

	/**
	 * @inheritDoc
	 */
	difference(other: AbstractModel): any {
		if (!(other instanceof PatientDetailModel)) {
			return {};
		}

		const diff = {};

		for (const key of _.keys(this)) {
			const thisValue = this[key];
			const otherValue = other[key];

			// Handle dates differently
			if (thisValue instanceof Date) {
				let thisDate = (thisValue) ? thisValue.getTime() : null;
				let otherDate = (otherValue) ? otherValue.getTime() : null;

				if (thisDate !== otherDate) {
					diff[key] = thisValue;
				}
			} else if (thisValue !== otherValue) {
				diff[key] = thisValue;
			}
		}

		return _.omit(diff, [
			'created',
			'modified',
			'patientGeneralInformationId',
			'patientGeneralInformation',
			// % protected region % [Add any other fields to omit here] off begin
			// % protected region % [Add any other fields to omit here] end
		]);
	}

	/**
	 * Sets the relation ID parameters to be based on the ID's of the associated entities.
	 * 
	 * Fetching entities is based on the object, but updating relations is based on the id, so we need to
	 * make sure that they match
	 */
	syncRelations() {
		if (!this.patientGeneralInformation) {
			this.patientGeneralInformationId = null;
		} else {
			this.patientGeneralInformationId = this.patientGeneralInformation.id;
		}

	}

	// % protected region % [Add any additional class methods here] off begin
	// % protected region % [Add any additional class methods here] end
}
