/*
 * @bot-written
 *
 * WARNING AND NOTICE
 * Any access, download, storage, and/or use of this source code is subject to the terms and conditions of the
 * Full Software Licence as accepted by you before being granted access to this source code and other materials,
 * the terms of which can be accessed on the Codebots website at https://codebots.com/full-software-licence. Any
 * commercial use in contravention of the terms of the Full Software Licence may be pursued by Codebots through
 * licence termination and further legal action, and be required to indemnify Codebots for any loss or damage,
 * including interest and costs. You are deemed to have accepted the terms of the Full Software Licence on any
 * access, download, storage, and/or use of this source code.
 *
 * BOT WARNING
 * This file is bot-written.
 * Any changes out side of "protected regions" will be lost next time the bot makes any changes.
 */
import {FormGroup, Validators} from '@angular/forms';
import {Group, AbstractModel, ModelProperty, ModelPropertyType, ModelRelation, ModelRelationType} from '../../lib/models/abstract.model';
import {DiagnosesAndProceduresModel} from '../diagnosesAndProcedures/diagnoses_and_procedures.model';
import {MedicalExaminationRecordModel} from '../medicalExaminationRecord/medical_examination_record.model';
import {OperatingTheaterMedicalExaminationRecordModel} from '../operatingTheaterMedicalExaminationRecord/operating_theater_medical_examination_record.model';
import * as _ from 'lodash';
import {QueryOperation, Where} from '../../lib/services/http/interfaces';
import {ElementType} from '../../lib/components/abstract.input.component';
import { CustomValidators } from 'src/app/lib/utils/validators/custom-validators';

// % protected region % [Add any additional imports here] off begin
// % protected region % [Add any additional imports here] end

/**
 * POJO model class used to store information related to the entity.
 */
export class DiagnosisNandaModel extends AbstractModel {
	/**
	 * The fields which are set as searchable in the entity model
	 * The fields could be used in search in the server side
	 * The fields would be by default used as search in the crud tile.
	 * You could also use this in other tiles for searching.
	 */
	static searchFields: string[] = [
		// % protected region % [Add any additional searchable field names here] off begin
		// % protected region % [Add any additional searchable field names here] end
	];

	/**
	 * Attributes to be shown in value to display
	 */
	static displayAttributes: string[] = [
		// % protected region % [Change displayAttributes here if needed] off begin
		'nursingNotes',
		// % protected region % [Change displayAttributes here if needed] end
	];

	static modelPropGroups: { [s: string]: Group } = {
		// % protected region % [Add groups for the entity here] off begin
		// % protected region % [Add groups for the entity here] end
	};

	readonly className = 'DiagnosisNandaModel';

	/**
	 * Default value to be displayed in dropdown etc
	 */
	get valueToDisplay(): string {
		// % protected region % [Change displayName here if needed] off begin
		return DiagnosisNandaModel.displayAttributes.map((attr) => this[attr]).join(' ');
		// % protected region % [Change displayName here if needed] end
	}

	/**
	 * Nursing Notes (Max Length: 5000).
	 */
	nursingNotes: string;

	/**
	 * Sequence with auto-generated by system counter from 1 (not shown on UI).
	 */
	sequence: number;

	medicalExaminationRecordId: string;

	medicalExaminationRecord: MedicalExaminationRecordModel;

	nursingAnesthesiaDetailIds: string[] = [];

	nursingAnesthesiaDetail: OperatingTheaterMedicalExaminationRecordModel[];

	nursingSurgicalDetailIds: string[] = [];

	nursingSurgicalDetail: OperatingTheaterMedicalExaminationRecordModel[];

	nursingIds: string[] = [];

	nursing: DiagnosesAndProceduresModel[];

	modelPropGroups: { [s: string]: Group } = DiagnosisNandaModel.modelPropGroups;

	// % protected region % [Add any additional class fields here] off begin
	// % protected region % [Add any additional class fields here] end

	static getProps(): ModelProperty[] {
		return super.getProps().concat([
			{
				name: 'nursingNotes',
				// % protected region % [Set displayName for Nursing Notes here] off begin
				displayName: 'Nursing Notes',
				// % protected region % [Set displayName for Nursing Notes here] end
				type: ModelPropertyType.STRING,
				// % protected region % [Set display element type for Nursing Notes here] off begin
				elementType: ElementType.INPUT,
				// % protected region % [Set display element type for Nursing Notes here] end
				// % protected region % [Set isSensitive for Nursing Notes here] off begin
				isSensitive: false,
				// % protected region % [Set isSensitive for Nursing Notes here] end
				// % protected region % [Set readonly for Nursing Notes here] off begin
				readOnly: false,
				// % protected region % [Set readonly for Nursing Notes here] end
				validators: [
					// % protected region % [Add other validators for Nursing Notes here] off begin
					// % protected region % [Add other validators for Nursing Notes here] end
				],
				// % protected region % [Add any additional model attribute properties for Nursing Notes here] off begin
				// % protected region % [Add any additional model attribute properties for Nursing Notes here] end
			},
			{
				name: 'sequence',
				// % protected region % [Set displayName for Sequence here] off begin
				displayName: 'Sequence',
				// % protected region % [Set displayName for Sequence here] end
				type: ModelPropertyType.NUMBER,
				// % protected region % [Set display element type for Sequence here] off begin
				elementType: ElementType.NUMBER,
				// % protected region % [Set display element type for Sequence here] end
				// % protected region % [Set isSensitive for Sequence here] off begin
				isSensitive: false,
				// % protected region % [Set isSensitive for Sequence here] end
				// % protected region % [Set readonly for Sequence here] off begin
				readOnly: false,
				// % protected region % [Set readonly for Sequence here] end
				validators: [
					// % protected region % [Add other validators for Sequence here] off begin
					// % protected region % [Add other validators for Sequence here] end
				],
				// % protected region % [Add any additional model attribute properties for Sequence here] off begin
				// % protected region % [Add any additional model attribute properties for Sequence here] end
			},
			// % protected region % [Add any additional class field names here] off begin
			// % protected region % [Add any additional class field names here] end
		]);
	}

	/**
	 * The relations of the entity
	 */
	static getRelations(): ModelRelation[] {
		return super.getRelations().concat([
			{
				id: 'nursingAnesthesiaDetail',
				type: ModelRelationType.MANY,
				name: 'nursingAnesthesiaDetailIds',
				// % protected region % [Customise your 1-1 or 1-M label for Nursing Anesthesia Detail here] off begin
				label: 'Nursing Anesthesia Detail',
				// % protected region % [Customise your 1-1 or 1-M label for Nursing Anesthesia Detail here] end
				entityName: 'OperatingTheaterMedicalExaminationRecordModel',
				// % protected region % [Customise your display name for Nursing Anesthesia Detail here] off begin
				displayName: 'hasConfirmedIdentity',
				// % protected region % [Customise your display name for Nursing Anesthesia Detail here] end
				validators: [
					// % protected region % [Add other validators for Nursing Anesthesia Detail here] off begin
					// % protected region % [Add other validators for Nursing Anesthesia Detail here] end
				],
				// % protected region % [Add any additional field for relation Nursing Anesthesia Detail here] off begin
				// % protected region % [Add any additional field for relation Nursing Anesthesia Detail here] end
			},
			{
				id: 'nursingSurgicalDetail',
				type: ModelRelationType.MANY,
				name: 'nursingSurgicalDetailIds',
				// % protected region % [Customise your 1-1 or 1-M label for Nursing Surgical Detail here] off begin
				label: 'Nursing Surgical Detail',
				// % protected region % [Customise your 1-1 or 1-M label for Nursing Surgical Detail here] end
				entityName: 'OperatingTheaterMedicalExaminationRecordModel',
				// % protected region % [Customise your display name for Nursing Surgical Detail here] off begin
				displayName: 'hasConfirmedIdentity',
				// % protected region % [Customise your display name for Nursing Surgical Detail here] end
				validators: [
					// % protected region % [Add other validators for Nursing Surgical Detail here] off begin
					// % protected region % [Add other validators for Nursing Surgical Detail here] end
				],
				// % protected region % [Add any additional field for relation Nursing Surgical Detail here] off begin
				// % protected region % [Add any additional field for relation Nursing Surgical Detail here] end
			},
			{
				id: 'medicalExaminationRecord',
				type: ModelRelationType.ONE,
				name: 'medicalExaminationRecordId',
				// % protected region % [Customise your label for Medical Examination Record here] off begin
				label: 'Medical Examination Record',
				// % protected region % [Customise your label for Medical Examination Record here] end
				entityName: 'MedicalExaminationRecordModel',
				// % protected region % [Customise your display name for Medical Examination Record here] off begin
				// TODO change implementation to use OrderBy or create new metamodel property DisplayBy
				displayName: 'diastole',
				// % protected region % [Customise your display name for Medical Examination Record here] end
				validators: [
					// % protected region % [Add other validators for Medical Examination Record here] off begin
					// % protected region % [Add other validators for Medical Examination Record here] end
				],
				// % protected region % [Add any additional field for relation Medical Examination Record here] off begin
				// % protected region % [Add any additional field for relation Medical Examination Record here] end
			},
			{
				id: 'nursing',
				type: ModelRelationType.MANY,
				name: 'nursingIds',
				// % protected region % [Customise your label for NURSING here] off begin
				label: 'NURSING',
				// % protected region % [Customise your label for NURSING here] end
				entityName: 'DiagnosesAndProceduresModel',
				// % protected region % [Customise your display name for NURSING here] off begin
				// TODO change implementation to use OrderBy or create new metamodel property DisplayBy
				displayName: 'itemType',
				// % protected region % [Customise your display name for NURSING here] end
				validators: [
					// % protected region % [Add other validators for NURSING here] off begin
					// % protected region % [Add other validators for NURSING here] end
				],
				// % protected region % [Add any additional field for relation NURSING here] off begin
				// % protected region % [Add any additional field for relation NURSING here] end
			},
		]);
	}

	/**
	 * Convert the form group to the query conditions
	 */
	static convertFilterToCondition(formGroup: FormGroup): Where[][] {
		let conditions: Where[][] = [];

		// % protected region % [Overide the default convertFilterToCondition here] off begin
		Object.keys(formGroup.value).forEach((key) => {
			switch (key) {
				case 'created':
					const created = formGroup.value[key];
					// is the range of date
					if (created instanceof Array) {
						conditions.push([
							{
								path: key,
								operation: QueryOperation.GREATER_THAN_OR_EQUAL,
								value: created[0]
							}
						]);
						conditions.push([
							{
								path: key,
								operation: QueryOperation.LESS_THAN_OR_EQUAL,
								value: created[1]
							}
						]);
					}
			}
		});
		// % protected region % [Overide the default convertFilterToCondition here] end


		return conditions;
	}

	/**
	 * Convert a nested JSON object into an array of flatten objects.
	 */
	static deepParse(data: string | { [K in keyof DiagnosisNandaModel]?: DiagnosisNandaModel[K] }, currentModel?): AbstractModel[] {
		if (currentModel == null) {
			currentModel = new DiagnosisNandaModel(data);
		}

		let returned: AbstractModel[] = [currentModel];
		const json = typeof data === 'string' ? JSON.parse(data) : data;

		// Incoming one to many
		if (json.medicalExaminationRecord) {
			currentModel.medicalExaminationRecordId = json.medicalExaminationRecord.id;
			returned = _.union(returned, MedicalExaminationRecordModel.deepParse(json.medicalExaminationRecord));
		}

		// Outgoing one to many
		if (json.nursingAnesthesiaDetail) {
			currentModel.nursingAnesthesiaDetailIds = json.nursingAnesthesiaDetail.map(model => model.id);
			returned = _.union(returned, _.flatten(json.nursingAnesthesiaDetail.map(model => OperatingTheaterMedicalExaminationRecordModel.deepParse(model))));
		}
		// Outgoing one to many
		if (json.nursingSurgicalDetail) {
			currentModel.nursingSurgicalDetailIds = json.nursingSurgicalDetail.map(model => model.id);
			returned = _.union(returned, _.flatten(json.nursingSurgicalDetail.map(model => OperatingTheaterMedicalExaminationRecordModel.deepParse(model))));
		}
		// Incoming many to many
		if (json.nursing) {
			currentModel.nursingIds = json.nursing.map(model => model.id);
			returned = _.union(returned, _.flatten(json.nursing.map(model => DiagnosesAndProceduresModel.deepParse(model))));
		}

		// % protected region % [Customise your deep parse before return here] off begin
		// % protected region % [Customise your deep parse before return here] end

		return returned;
	}

	/**
	 * @example
	 *
	 * `let diagnosisNandaModel = new DiagnosisNandaModel(data);`
	 *
	 * @param data The input data to be initialised as the DiagnosisNandaModel,
	 *    it is expected as a JSON string or as a nullable DiagnosisNandaModel.
	 */
	constructor(data?: string | Partial<DiagnosisNandaModel>) {
		super(data);

		if (data) {
			const json = typeof data === 'string'
				? JSON.parse(data) as Partial<DiagnosisNandaModel>
				: data;

			this.nursingNotes = json.nursingNotes;
			this.sequence = json.sequence;
			this.medicalExaminationRecordId = json.medicalExaminationRecordId;
			this.medicalExaminationRecord = json.medicalExaminationRecord;
			this.nursingAnesthesiaDetailIds = json.nursingAnesthesiaDetailIds;
			this.nursingAnesthesiaDetail = json.nursingAnesthesiaDetail;
			this.nursingSurgicalDetailIds = json.nursingSurgicalDetailIds;
			this.nursingSurgicalDetail = json.nursingSurgicalDetail;
			this.nursingIds = json.nursingIds;
			this.nursing = json.nursing;
			// % protected region % [Add any additional logic here after set the data] off begin
			// % protected region % [Add any additional logic here after set the data] end
		}

		// % protected region % [Add any additional constructor logic here] off begin
		// % protected region % [Add any additional constructor logic here] end
	}

	toJSON() {
		return {
			...super.toJSON(),
			nursingNotes: this.nursingNotes,
			sequence: this.sequence,
			medicalExaminationRecordId: this.medicalExaminationRecordId,
			nursingAnesthesiaDetailIds: this.nursingAnesthesiaDetailIds,
			nursingSurgicalDetailIds: this.nursingSurgicalDetailIds,
			nursingIds: this.nursingIds,
			// % protected region % [Add any additional logic here to json] off begin
			// % protected region % [Add any additional logic here to json] end
		};
	}

	getPropDisplayNames(): { [s: string]: ModelProperty } {
		const returned = {};
		DiagnosisNandaModel.getProps().map(prop => returned[prop.name] = prop);
		return returned;
	}

	applyUpdates(updates: any): DiagnosisNandaModel {
		let newModelJson = this.toJSON();

		if (updates.nursingNotes) {
			newModelJson.nursingNotes = updates.nursingNotes;
		}

		if (updates.sequence) {
			newModelJson.sequence = updates.sequence;
		}

		if (updates.medicalExaminationRecordId) {
			newModelJson.medicalExaminationRecordId = updates.medicalExaminationRecordId;
		}

		if (updates.nursingAnesthesiaDetailIds) {
			newModelJson.nursingAnesthesiaDetailIds = updates.nursingAnesthesiaDetailIds;
		}

		if (updates.nursingSurgicalDetailIds) {
			newModelJson.nursingSurgicalDetailIds = updates.nursingSurgicalDetailIds;
		}

		if (updates.nursingIds) {
			newModelJson.nursingIds = updates.nursingIds;
		}

		return new DiagnosisNandaModel(newModelJson);
	}

	/**
	 * @inheritDoc
	 */
	difference(other: AbstractModel): any {
		if (!(other instanceof DiagnosisNandaModel)) {
			return {};
		}

		const diff = {};

		for (const key of _.keys(this)) {
			const thisValue = this[key];
			const otherValue = other[key];

			// Handle dates differently
			if (thisValue instanceof Date) {
				let thisDate = (thisValue) ? thisValue.getTime() : null;
				let otherDate = (otherValue) ? otherValue.getTime() : null;

				if (thisDate !== otherDate) {
					diff[key] = thisValue;
				}
			} else if (thisValue !== otherValue) {
				diff[key] = thisValue;
			}
		}

		return _.omit(diff, [
			'created',
			'modified',
			'medicalExaminationRecordId',
			'medicalExaminationRecord',
			'nursingAnesthesiaDetailIds',
			'nursingAnesthesiaDetail',
			'nursingSurgicalDetailIds',
			'nursingSurgicalDetail',
			'nursingIds',
			'nursing',
			// % protected region % [Add any other fields to omit here] off begin
			// % protected region % [Add any other fields to omit here] end
		]);
	}

	/**
	 * Sets the relation ID parameters to be based on the ID's of the associated entities.
	 * 
	 * Fetching entities is based on the object, but updating relations is based on the id, so we need to
	 * make sure that they match
	 */
	syncRelations() {
		if (!this.medicalExaminationRecord) {
			this.medicalExaminationRecordId = null;
		} else {
			this.medicalExaminationRecordId = this.medicalExaminationRecord.id;
		}

	}

	// % protected region % [Add any additional class methods here] off begin
	// % protected region % [Add any additional class methods here] end
}
