/*
 * @bot-written
 *
 * WARNING AND NOTICE
 * Any access, download, storage, and/or use of this source code is subject to the terms and conditions of the
 * Full Software Licence as accepted by you before being granted access to this source code and other materials,
 * the terms of which can be accessed on the Codebots website at https://codebots.com/full-software-licence. Any
 * commercial use in contravention of the terms of the Full Software Licence may be pursued by Codebots through
 * licence termination and further legal action, and be required to indemnify Codebots for any loss or damage,
 * including interest and costs. You are deemed to have accepted the terms of the Full Software Licence on any
 * access, download, storage, and/or use of this source code.
 *
 * BOT WARNING
 * This file is bot-written.
 * Any changes out side of "protected regions" will be lost next time the bot makes any changes.
 */

import { ActivatedRoute } from '@angular/router';
import { BehaviorSubject } from 'rxjs';
import { By } from '@angular/platform-browser';
import { ComponentFixture, TestBed, waitForAsync, fakeAsync } from '@angular/core/testing';
import { CookieService } from 'ngx-cookie-service';
import { DebugElement } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { Store } from '@ngrx/store';
import { MockStore, provideMockStore } from '@ngrx/store/testing';
import { ModalDialogService, ModalDialogInstanceService } from '@preeco-privacy/ngx-modal-dialog';
import { ActivatedRouteStub } from 'src/testing/helpers/activated-route-stub';
import { CommonComponentModule } from 'src/app/lib/components/common.component.module';
import { getRouterState } from 'src/app/models/model.selector';
import { RouterState } from 'src/app/models/model.state';
import { 
	getChartOfAccountCollectionModels,
	getCountChartOfAccountModels,
	getChartOfAccountModelWithId
} from 'src/app/models/chartOfAccount/chart_of_account.model.selector';
import { ChartOfAccountCrudModule } from '../chart-of-account-crud.module';
import { ChartOfAccountCrudEditComponent } from './chart-of-account-crud-edit.component';
import {
	ChartOfAccountModelState,
	initialState as initialChartOfAccountModelState
} from 'src/app/models/chartOfAccount/chart_of_account.model.state';
import { ChartOfAccountDataFactory } from 'src/app/lib/utils/factories/chart-of-account-data-factory';
import { ChartOfAccountModel } from 'src/app/models/chartOfAccount/chart_of_account.model';
import { CrudTileMode } from '../chart-of-account-crud.component';
import { getChartOfAccountMappingModelWithId } from 'src/app/models/chartOfAccountMapping/chart_of_account_mapping.model.selector';
import { getChartOfAccountMappingCollectionModels } from 'src/app/models/chartOfAccountMapping/chart_of_account_mapping.model.selector';
import { ChartOfAccountMappingModel } from 'src/app/models/chartOfAccountMapping/chart_of_account_mapping.model';
import { ChartOfAccountMappingDataFactory } from 'src/app/lib/utils/factories/chart-of-account-mapping-data-factory';

describe('Chart of Account CRUD Edit component tests', () => {
	let fixture: ComponentFixture<ChartOfAccountCrudEditComponent>
	let component: ChartOfAccountCrudEditComponent;

	let chartOfAccountModelState: ChartOfAccountModelState;

	let store: MockStore<{ model: ChartOfAccountModelState }>;
	let routerStore: MockStore<{router: RouterState}>;

	let routerStateBehaviorSubject: BehaviorSubject<RouterState>;
	let chartOfAccountCountBehaviorSubject: BehaviorSubject<number>;
	let chartOfAccountModelsBehaviorSubject: BehaviorSubject<ChartOfAccountModel[]>;
	let chartOfAccountMappingModelsBehaviorSubject: BehaviorSubject<ChartOfAccountMappingModel[]>;

	const chartOfAccountFactory: ChartOfAccountDataFactory = new ChartOfAccountDataFactory();
	const defaultChartOfAccountCount: number = 10;
	const defaultChartOfAccountEntities: ChartOfAccountModel[] = chartOfAccountFactory.createAll(defaultChartOfAccountCount);

	const chartOfAccountMappingFactory: ChartOfAccountMappingDataFactory = new ChartOfAccountMappingDataFactory();
	const defaultChartOfAccountMappingCount: number = 10;
	const defaultChartOfAccountMappingEntities: ChartOfAccountMappingModel[] = chartOfAccountMappingFactory.createAll(defaultChartOfAccountMappingCount);


	// We define the entity which is used in edit mode after all of the other entities because we can now
	// use the data already generated by the previous entity factories to populate the relations of this entity
	let chartOfAccountWithId: ChartOfAccountModel = defaultChartOfAccountEntities[0];
	let chartOfAccountModelWithIdBehaviorSubject: BehaviorSubject<ChartOfAccountModel>;

	chartOfAccountWithId.chartOfAccountMappings = defaultChartOfAccountMappingEntities;
	chartOfAccountWithId.chartOfAccountMappingsIds = chartOfAccountWithId.chartOfAccountMappings.map(chartOfAccountMappings => chartOfAccountMappings.id);


	const routerState: RouterState = {
		url: 'chart-of-account-crud',
		urls: ['chart-of-account-crud'],
		params: {},
		queryParams: {},
		data: {},
	};

	function spySelectorsInStore() {
		// Setup the Mock Store and fake selector
		store = TestBed.inject(Store) as MockStore<{ model: ChartOfAccountModelState }>;
		routerStore = TestBed.inject(Store) as MockStore<{ router: RouterState }>;

		chartOfAccountModelState = initialChartOfAccountModelState;
		store.setState({model: chartOfAccountModelState});
		routerStateBehaviorSubject = new BehaviorSubject(routerState);
		chartOfAccountCountBehaviorSubject = new BehaviorSubject(defaultChartOfAccountCount);

		// selectors for all references
		chartOfAccountModelsBehaviorSubject = new BehaviorSubject(defaultChartOfAccountEntities);
		chartOfAccountMappingModelsBehaviorSubject = new BehaviorSubject(defaultChartOfAccountMappingEntities);

		// selectors for target entity and its related entity
		chartOfAccountModelWithIdBehaviorSubject = new BehaviorSubject(chartOfAccountWithId);

		spyOn(store, 'select')
			.withArgs(getCountChartOfAccountModels).and.returnValue(chartOfAccountCountBehaviorSubject)
			.withArgs(getChartOfAccountModelWithId, chartOfAccountWithId.id).and.returnValue(chartOfAccountModelWithIdBehaviorSubject)
			.withArgs(getChartOfAccountCollectionModels, jasmine.any(String)).and.returnValue(chartOfAccountModelsBehaviorSubject)
			.withArgs(getChartOfAccountMappingCollectionModels, jasmine.any(String)).and.returnValue(chartOfAccountMappingModelsBehaviorSubject)
			.withArgs(getRouterState).and.returnValue(routerStateBehaviorSubject);
	}

	beforeEach(waitForAsync (() => {

		const activatedRouteStub = new ActivatedRouteStub();

		TestBed.configureTestingModule({
			imports: [
				HttpClientTestingModule,
				ChartOfAccountCrudModule,
				CommonComponentModule,
				FormsModule,
				ReactiveFormsModule,
			],
			providers: [
				provideMockStore(),
				{
					provide: ActivatedRoute,
					useValue: activatedRouteStub,
				},
				CookieService,
				ModalDialogService,
				ModalDialogInstanceService,
			]
		}).compileComponents().then(() => {

			spySelectorsInStore();

			fixture = TestBed.createComponent(ChartOfAccountCrudEditComponent);
			component = fixture.debugElement.componentInstance;
			component.ngOnInit();
			component.targetModel = new ChartOfAccountModel();
			component.createReactiveForm();
			fixture.detectChanges();


		});
	}));

	afterEach(() => {
		// Need to do this since for some reason the last component queried from the fixture will be rendered on the
		// browser
		if (fixture.nativeElement instanceof HTMLElement) {
			(fixture.nativeElement as HTMLElement).remove();
		}
		component.ngOnDestroy();
	});

	/**
	 * Checks that the component is created by the test initialisation
	 */
	it ('Renders the Chart of Account CRUD Edit Component', () => {
		expect(component).toBeTruthy();
	});

	/**
	 * Checks that there are no add additional model buttons present in the component when in view mode.
	 *
	 * This test does not require checking whether multi crud is active for a given relation, as the expected outcome
	 * is identical for components with multi entity crud active and for components without it
	 */
	it ('Does not render any add entity buttons when in view mode', fakeAsync(() => {
		component.tileMode = CrudTileMode.View;
		fixture.detectChanges();

		const addEntityButtons: DebugElement[] = fixture.debugElement
				.queryAll(By.css('button.btn__add-entity'));

		expect(addEntityButtons.length).toEqual(0);
	}));

	/**
	* Checks that the status of the add model button matches the multi entity status for the Chart of Account Mappings relation.
	*
	* The button should only exist if chartOfAccountMappingsMultiCrudActive is true
	*/
	it ('Renders Chart of Account Mappings Add Entity button in create mode', fakeAsync(() => {
		const chartOfAccountMappingsButton: DebugElement = fixture.debugElement
				.queryAll(By.css('button.btn__add-entity'))
				.find(element => element.nativeElement.textContent.includes('Add New ' + component.chartOfAccountMappingsDisplayName + ' to Model'));

		// For this test we don't need to interact with the button, as we are looking to prove that it exists and is present on the page
		// prepending the element with `!!` will turn the object into a boolean which is true if the element exists and false otherwise
		// If multi crud is off for this entity, then we expect the button to not exist, so we can check for equality with the MultiCrudActive attribute
		expect(!!chartOfAccountMappingsButton).toEqual(component.chartOfAccountMappingsMultiCrudActive);
	}));


	it ('Adds a new entity to the page when clicking button to add new Chart of Account Mappings', fakeAsync(() => {
		const chartOfAccountMappingsButton: DebugElement = fixture.debugElement
				.queryAll(By.css('button.btn__add-entity'))
				.find(element => element.nativeElement.textContent.includes('Add New ' + component.chartOfAccountMappingsDisplayName + ' to Model'));

		// Any expectations beyond this will only be run if multi crud is active for this entity
		// We can't run the test conditionally as the value we need to check by is set asyncronously during setup
		// We also don't want tests without any conditions, so adding this check here was deemed to be the cleanest option for now
		expect(!!chartOfAccountMappingsButton).toEqual(component.chartOfAccountMappingsMultiCrudActive);

		if (component.chartOfAccountMappingsMultiCrudActive) {
			// After clicking the add entity button, we will expect that the number of these buttons increases
			// We store this value now so that we can access it following interaction with the component
			const initialChartOfAccountMappingsRemoveButtonCount = fixture.debugElement
					.queryAll(By.css('button.btn__remove-entity'))
					.filter(element => element.nativeElement.textContent.includes('Remove ' + component.chartOfAccountMappingsDisplayName + ' from Model')).length;

			chartOfAccountMappingsButton.nativeElement.click();
			fixture.detectChanges();

			const actualChartOfAccountMappingsRemoveButtonCount = fixture.debugElement
					.queryAll(By.css('button.btn__remove-entity'))
					.filter(element => element.nativeElement.textContent.includes('Remove ' + component.chartOfAccountMappingsDisplayName + ' from Model')).length;

			expect(actualChartOfAccountMappingsRemoveButtonCount).toEqual(initialChartOfAccountMappingsRemoveButtonCount + 1);
		}
	}));

	it ('Removes an additional entity from the page when clicking remove Chart of Account Mappings button', () => {
		const chartOfAccountMappingsButton: DebugElement = fixture.debugElement
				.queryAll(By.css('button.btn__add-entity'))
				.find(element => element.nativeElement.textContent.includes('Add New ' + component.chartOfAccountMappingsDisplayName + ' to Model'));

		// Any expectations beyond this will only be run if multi crud is active for this entity
		// We can't run the test conditionally as the value we need to check by is set asyncronously during setup
		// We also don't want tests without any conditions, so adding this check here was deemed to be the cleanest option for now
		expect(!!chartOfAccountMappingsButton).toEqual(component.chartOfAccountMappingsMultiCrudActive);

		if (component.chartOfAccountMappingsMultiCrudActive) {
			// This test is examining whether clicking the remove button will remove an additional entity.
			// By default there will be no remove buttons, so first we need to add an entity so we can test removal
			chartOfAccountMappingsButton.nativeElement.click();
			fixture.detectChanges();

			// create an array of elements here as opposed to just getting the length (like in previous tests)
			// as we need to interact with the button in this test
			const initialChartOfAccountMappingsRemoveButtons = fixture.debugElement
					.queryAll(By.css('button.btn__remove-entity'))
					.filter(element => element.nativeElement.textContent.includes('Remove ' + component.chartOfAccountMappingsDisplayName + ' from Model'));

			// As we have already tested that clicking the add button adds the element, we know there will be at lease one button here to click
			initialChartOfAccountMappingsRemoveButtons[0].nativeElement.click();
			fixture.detectChanges();

			const actualChartOfAccountMappingsRemoveButtons = fixture.debugElement
					.queryAll(By.css('button.btn__remove-entity'))
					.filter(element => element.nativeElement.textContent.includes('Remove ' + component.chartOfAccountMappingsDisplayName + ' from Model'));

			expect(actualChartOfAccountMappingsRemoveButtons.length).toEqual(initialChartOfAccountMappingsRemoveButtons.length - 1);
		}
	});

	it ('should not disable the add Chart of Account Mappings button when one has already been added', () => {

		const chartOfAccountMappingsButton: DebugElement = fixture.debugElement
		.queryAll(By.css('button.btn__add-entity'))
		.find(element => element.nativeElement.textContent.includes('Add New ' + component.chartOfAccountMappingsDisplayName + ' to Model'));

		// Any expectations beyond this will only be run if multi crud is active for this entity
		// We can't run the test conditionally as the value we need to check by is set asyncronously during setup
		// We also don't want tests without any conditions, so adding this check here was deemed to be the cleanest option for now
		expect(!!chartOfAccountMappingsButton).toEqual(component.chartOfAccountMappingsMultiCrudActive);

		if (component.chartOfAccountMappingsMultiCrudActive) {
			chartOfAccountMappingsButton.nativeElement.click();
			fixture.detectChanges();

			const updatedchartOfAccountMappingsButton: DebugElement = fixture.debugElement
					.queryAll(By.css('button.btn__add-entity'))
					.find(element => element.nativeElement.textContent.includes('Add New ' + component.chartOfAccountMappingsDisplayName + ' to Model'));

			expect(updatedchartOfAccountMappingsButton.nativeElement.disabled).toBe(false);
		}
	});

	it ('renders related Chart of Account Mappings entities from model when loading in edit mode', () => {
		component.targetModel = chartOfAccountWithId;
		component.targetModelId = chartOfAccountWithId.id;
		component.tileMode = CrudTileMode.Edit;
		component.ngOnInit();
		component.createReactiveForm();
		component.multiCrudFetchAdditionalEntities();
		fixture.detectChanges();

		if (component.chartOfAccountMappingsMultiCrudActive) {
			// As there is always one remove button per additional entity, running a test against the number of remove buttons is a simple
			// and reliable method to determine how many entities of the given type are present in the crud page
			const chartOfAccountMappingsRemoveButtonCount = fixture.debugElement
				.queryAll(By.css('button.btn__remove-entity'))
				.filter(element => element.nativeElement.textContent.includes('Remove ' + component.chartOfAccountMappingsDisplayName + ' from Model')).length;

			expect(chartOfAccountMappingsRemoveButtonCount).toEqual(chartOfAccountWithId.chartOfAccountMappings.length);
		}
	});

});
